### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Newar417** [DJM0/Gridseed-PiMiner#1]
Line 40: To fully update the RPi you'll need to run `apt-get upgrade` too. `apt-get update` only gets the packages lists. Might want to add `apt-get dist-upgrade` as well :-)

**Comment by DJM0** [comment]
Hi Newar417, at the moment we are only updating the package lists for the actual packages we need to install (see the line 41).

We may change it to update all system packages but obviously this will push the install time up. We won't do a `dist-upgrade` as this is really for the user to decide.

**Comment by Newar417** [comment]
Oh, ok. I was just thinking because it says it will update system packages.
