### ISSUE TITLE
Watchdog

### ISSUE THREAD

**Issue by Newar417** [DJM0/Gridseed-PiMiner#2]
I had `watchdog` installed already (I know you said to use a clean system...)

update-rc.d: using dependency based boot sequencing
insserv: warning: script 'miner-boot.sh' missing LSB tags and overrides
insserv: There is a loop between service watchdog and miner-boot.sh if stopped
insserv:  loop involving service miner-boot.sh at depth 2
insserv:  loop involving service watchdog at depth 1
insserv: Stopping miner-boot.sh depends on watchdog and therefore on system facility `$all' which can not be true!
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header

**Comment by DJM0** [comment]
Will have a look into this but we haven't tested with watchdog installed, so will have to give it a go.

Let us know if you have a fix.

**Comment by Newar417** [comment]
Well, my "fix" is to put the miner launcher script in `/etc/rc.local`. I have some other stuff in it, in case cgminer crashes.

Maybe `crontab` @reboot could work too.

**Comment by DJM0** [comment]
Closing as project no longer under active development.
